# Generated by Django 2.1.2 on 2018-10-26 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pagina', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='Telefono',
            field=models.IntegerField(max_length=8),
        ),
    ]
