# Generated by Django 2.1.2 on 2018-10-26 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pagina', '0005_persona_tipo_casa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perro',
            name='Estado',
            field=models.CharField(choices=[('I', 'Seleccione'), ('R', 'Rescatado'), ('D', 'Disponible'), ('A', 'Adoptado')], default='I', max_length=1),
        ),
        migrations.AlterField(
            model_name='persona',
            name='Tipo_casa',
            field=models.CharField(choices=[('I', 'Seleccione'), ('G', 'Patio Grande'), ('P', 'Patio Pequeño'), ('D', 'Departamento'), ('S', 'Sin Patio')], default='I', max_length=1),
        ),
    ]
