# Generated by Django 2.1.2 on 2018-10-26 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pagina', '0007_auto_20181026_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perro',
            name='Estado',
            field=models.CharField(choices=[('I', 'Seleccionar'), ('R', 'Rescatado'), ('D', 'Disponible'), ('A', 'Adoptado')], default='D', max_length=1),
        ),
        migrations.AlterField(
            model_name='persona',
            name='Tipo_casa',
            field=models.CharField(choices=[('G', 'Patio Grande'), ('P', 'Patio Pequeño'), ('D', 'Departamento'), ('S', 'Sin Patio')], default='S', max_length=1),
        ),
    ]
