# Generated by Django 2.1.2 on 2018-10-30 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pagina', '0008_auto_20181026_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='Tipo_casa',
            field=models.IntegerField(choices=[(1, 'Patio Grande'), (2, 'Patio Pequeño'), (3, 'Sin Patio'), (4, 'Departamento')], default=1),
        ),
    ]
