# Generated by Django 2.1.2 on 2018-10-30 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pagina', '0009_auto_20181029_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perro',
            name='Estado',
            field=models.IntegerField(choices=[(1, 'Rescatado'), (2, 'Disponible'), (3, 'Adoptado')], default=2),
        ),
    ]
