# Generated by Django 2.1.2 on 2018-10-30 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pagina', '0010_auto_20181029_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='Region',
            field=models.IntegerField(choices=[(1, 'Arica y Parinacota'), (2, 'Tarapacá'), (3, 'Antofagasta'), (4, 'Atacama'), (5, 'Coquimbo'), (6, 'Valparaíso'), (7, 'Región del Libertador Gral. Bernardo O’Higgins'), (8, 'Región del Maule'), (9, 'Región del Biobío'), (10, 'Región de la Araucanía'), (11, 'Región de Los Ríos'), (12, 'Región de Los Lagos'), (13, 'Región Aisén del Gral. Carlos Ibáñez del Campo'), (14, 'Región de Magallanes y de la AntárVca Chilena'), (15, 'Región Metropolitana de Santiago')], default=1),
        ),
    ]
