# Generated by Django 2.1.2 on 2018-10-31 02:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pagina', '0013_persona_comuna'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='Fecha_nacimiento',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
