# Generated by Django 2.1.2 on 2018-10-31 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pagina', '0014_persona_fecha_nacimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='perro',
            name='Imagen',
            field=models.FileField(blank=True, upload_to='post_image'),
        ),
    ]
