# Generated by Django 2.1.2 on 2018-10-31 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pagina', '0015_perro_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perro',
            name='Imagen',
            field=models.ImageField(blank=True, upload_to='photos'),
        ),
    ]
