# Generated by Django 2.1.2 on 2018-11-05 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pagina', '0016_auto_20181031_0007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='id',
        ),
        migrations.AddField(
            model_name='persona',
            name='id_persona',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
