# Generated by Django 2.1.2 on 2018-11-05 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pagina', '0017_auto_20181104_2229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='id_persona',
        ),
        migrations.AddField(
            model_name='persona',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
