TIPO_CASAS = (
    (1, ("Patio Grande")),
    (2, ("Patio Pequeño")),
    (3, ("Sin Patio")),
    (4, ("Departamento"))
)

ESTADO_PERRO = (
    (1, ("Rescatado")),
    (2, ("Disponible")),
    (3, ("Adoptado"))
)

LIST_REGION = (
    (1, ("Arica y Parinacota")),
    (2, ("Tarapacá")),
    (3, ("Antofagasta")),
    (4, ("Atacama")),
    (5, ("Coquimbo")),
    (6, ("Valparaíso")),
    (7, ("Región del Libertador Gral. Bernardo O’Higgins")),
    (8, ("Región del Maule")),
    (9, ("Región del Biobío")),
    (10, ("Región de la Araucanía")),
    (11, ("Región de Los Ríos")),
    (12, ("Región de Los Lagos")),
    (13, ("Región Aisén del Gral. Carlos Ibáñez del Campo")),
    (14, ("Región de Magallanes y de la AntárVca Chilena")),
    (15, ("Región Metropolitana de Santiago"))
)  


LIST_COMUNA = (
    (	1	,	(	"	Arica	"	)	)	,
(	2	,	(	"	Camarones	"	)	)	,
(	3	,	(	"	Putre	"	)	)	,
(	4	,	(	"	General Lagos	"	)	)	,
(	5	,	(	"	Iquique	"	)	)	,
(	6	,	(	"	Camiña	"	)	)	,
(	7	,	(	"	Colchane	"	)	)	,
(	8	,	(	"	Huara	"	)	)	,
(	9	,	(	"	Pica	"	)	)	,
(	10	,	(	"	Pozo Almonte	"	)	)	,
(	11	,	(	"	Alto Hospicio	"	)	)	,
(	12	,	(	"	Antofagasta	"	)	)	,
(	13	,	(	"	Mejillones	"	)	)	,
(	14	,	(	"	Sierra Gorda	"	)	)	,
(	15	,	(	"	Taltal	"	)	)	,
(	16	,	(	"	Calama	"	)	)	,
(	17	,	(	"	Ollagüe	"	)	)	,
(	18	,	(	"	San Pedro de Atacama	"	)	)	,
(	19	,	(	"	Tocopilla	"	)	)	,
(	20	,	(	"	María Elena	"	)	)	,
(	21	,	(	"	Copiapó	"	)	)	,
(	22	,	(	"	Caldera	"	)	)	,
(	23	,	(	"	Tierra Amarilla	"	)	)	,
(	24	,	(	"	Chañaral	"	)	)	,
(	25	,	(	"	Diego de Almagro	"	)	)	,
(	26	,	(	"	Vallenar	"	)	)	,
(	27	,	(	"	Alto del Carmen	"	)	)	,
(	28	,	(	"	Freirina	"	)	)	,
(	29	,	(	"	Huasco	"	)	)	,
(	30	,	(	"	La Serena	"	)	)	,
(	31	,	(	"	Coquimbo	"	)	)	,
(	32	,	(	"	Andacollo	"	)	)	,
(	33	,	(	"	La Higuera	"	)	)	,
(	34	,	(	"	Paiguano	"	)	)	,
(	35	,	(	"	Vicuña	"	)	)	,
(	36	,	(	"	Illapel	"	)	)	,
(	37	,	(	"	Canela	"	)	)	,
(	38	,	(	"	Los Vilos	"	)	)	,
(	39	,	(	"	Salamanca	"	)	)	,
(	40	,	(	"	Ovalle	"	)	)	,
(	41	,	(	"	Combarbalá	"	)	)	,
(	42	,	(	"	Monte Patria	"	)	)	,
(	43	,	(	"	Punitaqui	"	)	)	,
(	44	,	(	"	Río Hurtado	"	)	)	,
(	45	,	(	"	Valparaíso	"	)	)	,
(	46	,	(	"	Casablanca	"	)	)	,
(	47	,	(	"	Concón	"	)	)	,
(	48	,	(	"	Juan Fernández	"	)	)	,
(	49	,	(	"	Puchuncaví	"	)	)	,
(	50	,	(	"	Quilpué	"	)	)	,
(	51	,	(	"	Quintero	"	)	)	,
(	52	,	(	"	Villa Alemana	"	)	)	,
(	53	,	(	"	Viña del Mar	"	)	)	,
(	54	,	(	"	Isla  de Pascua	"	)	)	,
(	55	,	(	"	Los Andes	"	)	)	,
(	56	,	(	"	Calle Larga	"	)	)	,
(	57	,	(	"	Rinconada	"	)	)	,
(	58	,	(	"	San Esteban	"	)	)	,
(	59	,	(	"	La Ligua	"	)	)	,
(	60	,	(	"	Cabildo	"	)	)	,
(	61	,	(	"	Papudo	"	)	)	,
(	62	,	(	"	Petorca	"	)	)	,
(	63	,	(	"	Zapallar	"	)	)	,
(	64	,	(	"	Quillota	"	)	)	,
(	65	,	(	"	Calera	"	)	)	,
(	66	,	(	"	Hijuelas	"	)	)	,
(	67	,	(	"	La Cruz	"	)	)	,
(	68	,	(	"	Limache	"	)	)	,
(	69	,	(	"	Nogales	"	)	)	,
(	70	,	(	"	Olmué	"	)	)	,
(	71	,	(	"	San Antonio	"	)	)	,
(	72	,	(	"	Algarrobo	"	)	)	,
(	73	,	(	"	Cartagena	"	)	)	,
(	74	,	(	"	El Quisco	"	)	)	,
(	75	,	(	"	El Tabo	"	)	)	,
(	76	,	(	"	Santo Domingo	"	)	)	,
(	77	,	(	"	San Felipe	"	)	)	,
(	78	,	(	"	Catemu	"	)	)	,
(	79	,	(	"	Llaillay	"	)	)	,
(	80	,	(	"	Panquehue	"	)	)	,
(	81	,	(	"	Putaendo	"	)	)	,
(	82	,	(	"	Santa María	"	)	)	,
(	83	,	(	"	Rancagua	"	)	)	,
(	84	,	(	"	Codegua	"	)	)	,
(	85	,	(	"	Coinco	"	)	)	,
(	86	,	(	"	Coltauco	"	)	)	,
(	87	,	(	"	Doñihue	"	)	)	,
(	88	,	(	"	Graneros	"	)	)	,
(	89	,	(	"	Las Cabras	"	)	)	,
(	90	,	(	"	Machalí	"	)	)	,
(	91	,	(	"	Malloa	"	)	)	,
(	92	,	(	"	Mostazal	"	)	)	,
(	93	,	(	"	Olivar	"	)	)	,
(	94	,	(	"	Peumo	"	)	)	,
(	95	,	(	"	Pichidegua	"	)	)	,
(	96	,	(	"	Quinta de Tilcoco	"	)	)	,
(	97	,	(	"	Rengo	"	)	)	,
(	98	,	(	"	Requínoa	"	)	)	,
(	99	,	(	"	San Vicente	"	)	)	,
(	100	,	(	"	Pichilemu	"	)	)	,
(	101	,	(	"	La Estrella	"	)	)	,
(	102	,	(	"	Litueche	"	)	)	,
(	103	,	(	"	Marchihue	"	)	)	,
(	104	,	(	"	Navidad	"	)	)	,
(	105	,	(	"	Paredones	"	)	)	,
(	106	,	(	"	San Fernando	"	)	)	,
(	107	,	(	"	Chépica	"	)	)	,
(	108	,	(	"	Chimbarongo	"	)	)	,
(	109	,	(	"	Lolol	"	)	)	,
(	110	,	(	"	Nancagua	"	)	)	,
(	111	,	(	"	Palmilla	"	)	)	,
(	112	,	(	"	Peralillo	"	)	)	,
(	113	,	(	"	Placilla	"	)	)	,
(	114	,	(	"	Pumanque	"	)	)	,
(	115	,	(	"	Santa Cruz	"	)	)	,
(	116	,	(	"	Talca	"	)	)	,
(	117	,	(	"	Constitución	"	)	)	,
(	118	,	(	"	Curepto	"	)	)	,
(	119	,	(	"	Empedrado	"	)	)	,
(	120	,	(	"	Maule	"	)	)	,
(	121	,	(	"	Pelarco	"	)	)	,
(	122	,	(	"	Pencahue	"	)	)	,
(	123	,	(	"	Río Claro	"	)	)	,
(	124	,	(	"	San Clemente	"	)	)	,
(	125	,	(	"	San Rafael	"	)	)	,
(	126	,	(	"	Cauquenes	"	)	)	,
(	127	,	(	"	Chanco	"	)	)	,
(	128	,	(	"	Pelluhue	"	)	)	,
(	129	,	(	"	Curicó	"	)	)	,
(	130	,	(	"	Hualañé	"	)	)	,
(	131	,	(	"	Licantén	"	)	)	,
(	132	,	(	"	Molina	"	)	)	,
(	133	,	(	"	Rauco	"	)	)	,
(	134	,	(	"	Romeral	"	)	)	,
(	135	,	(	"	Sagrada Familia	"	)	)	,
(	136	,	(	"	Teno	"	)	)	,
(	137	,	(	"	Vichuquén	"	)	)	,
(	138	,	(	"	Linares	"	)	)	,
(	139	,	(	"	Colbún	"	)	)	,
(	140	,	(	"	Longaví	"	)	)	,
(	141	,	(	"	Parral	"	)	)	,
(	142	,	(	"	Retiro	"	)	)	,
(	143	,	(	"	San Javier	"	)	)	,
(	144	,	(	"	Villa Alegre	"	)	)	,
(	145	,	(	"	Yerbas Buenas	"	)	)	,
(	146	,	(	"	Concepción	"	)	)	,
(	147	,	(	"	Coronel	"	)	)	,
(	148	,	(	"	Chiguayante	"	)	)	,
(	149	,	(	"	Florida	"	)	)	,
(	150	,	(	"	Hualqui	"	)	)	,
(	151	,	(	"	Lota	"	)	)	,
(	152	,	(	"	Penco	"	)	)	,
(	153	,	(	"	San Pedro de la Paz	"	)	)	,
(	154	,	(	"	Santa Juana	"	)	)	,
(	155	,	(	"	Talcahuano	"	)	)	,
(	156	,	(	"	Tomé	"	)	)	,
(	157	,	(	"	Hualpén	"	)	)	,
(	158	,	(	"	Lebu	"	)	)	,
(	159	,	(	"	Arauco	"	)	)	,
(	160	,	(	"	Cañete	"	)	)	,
(	161	,	(	"	Contulmo	"	)	)	,
(	162	,	(	"	Curanilahue	"	)	)	,
(	163	,	(	"	Los Álamos	"	)	)	,
(	164	,	(	"	Tirúa	"	)	)	,
(	165	,	(	"	Los Ángeles	"	)	)	,
(	166	,	(	"	Antuco	"	)	)	,
(	167	,	(	"	Cabrero	"	)	)	,
(	168	,	(	"	Laja	"	)	)	,
(	169	,	(	"	Mulchén	"	)	)	,
(	170	,	(	"	Nacimiento	"	)	)	,
(	171	,	(	"	Negrete	"	)	)	,
(	172	,	(	"	Quilaco	"	)	)	,
(	173	,	(	"	Quilleco	"	)	)	,
(	174	,	(	"	San Rosendo	"	)	)	,
(	175	,	(	"	Santa Bárbara	"	)	)	,
(	176	,	(	"	Tucapel	"	)	)	,
(	177	,	(	"	Yumbel	"	)	)	,
(	178	,	(	"	Alto Biobío	"	)	)	,
(	179	,	(	"	Chillán	"	)	)	,
(	180	,	(	"	Bulnes	"	)	)	,
(	181	,	(	"	Cobquecura	"	)	)	,
(	182	,	(	"	Coelemu	"	)	)	,
(	183	,	(	"	Coihueco	"	)	)	,
(	184	,	(	"	Chillán Viejo	"	)	)	,
(	185	,	(	"	El Carmen	"	)	)	,
(	186	,	(	"	Ninhue	"	)	)	,
(	187	,	(	"	Ñiquén	"	)	)	,
(	188	,	(	"	Pemuco	"	)	)	,
(	189	,	(	"	Pinto	"	)	)	,
(	190	,	(	"	Portezuelo	"	)	)	,
(	191	,	(	"	Quillón	"	)	)	,
(	192	,	(	"	Quirihue	"	)	)	,
(	193	,	(	"	Ránquil	"	)	)	,
(	194	,	(	"	San Carlos	"	)	)	,
(	195	,	(	"	San Fabián	"	)	)	,
(	196	,	(	"	San Ignacio	"	)	)	,
(	197	,	(	"	San Nicolás	"	)	)	,
(	198	,	(	"	Treguaco	"	)	)	,
(	199	,	(	"	Yungay	"	)	)	,
(	200	,	(	"	Temuco	"	)	)	,
(	201	,	(	"	Carahue	"	)	)	,
(	202	,	(	"	Cunco	"	)	)	,
(	203	,	(	"	Curarrehue	"	)	)	,
(	204	,	(	"	Freire	"	)	)	,
(	205	,	(	"	Galvarino	"	)	)	,
(	206	,	(	"	Gorbea	"	)	)	,
(	207	,	(	"	Lautaro	"	)	)	,
(	208	,	(	"	Loncoche	"	)	)	,
(	209	,	(	"	Melipeuco	"	)	)	,
(	210	,	(	"	Nueva Imperial	"	)	)	,
(	211	,	(	"	Padre Las Casas	"	)	)	,
(	212	,	(	"	Perquenco	"	)	)	,
(	213	,	(	"	Pitrufquén	"	)	)	,
(	214	,	(	"	Pucón	"	)	)	,
(	215	,	(	"	Saavedra	"	)	)	,
(	216	,	(	"	Teodoro Schmidt	"	)	)	,
(	217	,	(	"	Toltén	"	)	)	,
(	218	,	(	"	Vilcún	"	)	)	,
(	219	,	(	"	Villarrica	"	)	)	,
(	220	,	(	"	Cholchol	"	)	)	,
(	221	,	(	"	Angol	"	)	)	,
(	222	,	(	"	Collipulli	"	)	)	,
(	223	,	(	"	Curacautín	"	)	)	,
(	224	,	(	"	Ercilla	"	)	)	,
(	225	,	(	"	Lonquimay	"	)	)	,
(	226	,	(	"	Los Sauces	"	)	)	,
(	227	,	(	"	Lumaco	"	)	)	,
(	228	,	(	"	Purén	"	)	)	,
(	229	,	(	"	Renaico	"	)	)	,
(	230	,	(	"	Traiguén	"	)	)	,
(	231	,	(	"	Victoria	"	)	)	,
(	232	,	(	"	Valdivia	"	)	)	,
(	233	,	(	"	Corral	"	)	)	,
(	234	,	(	"	Futrono	"	)	)	,
(	235	,	(	"	La Unión	"	)	)	,
(	236	,	(	"	Lago Ranco	"	)	)	,
(	237	,	(	"	Lanco	"	)	)	,
(	238	,	(	"	Los Lagos	"	)	)	,
(	239	,	(	"	Máfil	"	)	)	,
(	240	,	(	"	Mariquina	"	)	)	,
(	241	,	(	"	Paillaco	"	)	)	,
(	242	,	(	"	Panguipulli	"	)	)	,
(	243	,	(	"	Río Bueno	"	)	)	,
(	244	,	(	"	Puerto Montt	"	)	)	,
(	245	,	(	"	Calbuco	"	)	)	,
(	246	,	(	"	Cochamó	"	)	)	,
(	247	,	(	"	Fresia	"	)	)	,
(	248	,	(	"	Frutillar	"	)	)	,
(	249	,	(	"	Los Muermos	"	)	)	,
(	250	,	(	"	Llanquihue	"	)	)	,
(	251	,	(	"	Maullín	"	)	)	,
(	252	,	(	"	Puerto Varas	"	)	)	,
(	253	,	(	"	Castro	"	)	)	,
(	254	,	(	"	Ancud	"	)	)	,
(	255	,	(	"	Chonchi	"	)	)	,
(	256	,	(	"	Curaco de Vélez	"	)	)	,
(	257	,	(	"	Dalcahue	"	)	)	,
(	258	,	(	"	Puqueldón	"	)	)	,
(	259	,	(	"	Queilén	"	)	)	,
(	260	,	(	"	Quellón	"	)	)	,
(	261	,	(	"	Quemchi	"	)	)	,
(	262	,	(	"	Quinchao	"	)	)	,
(	263	,	(	"	Osorno	"	)	)	,
(	264	,	(	"	Puerto Octay	"	)	)	,
(	265	,	(	"	Purranque	"	)	)	,
(	266	,	(	"	Puyehue	"	)	)	,
(	267	,	(	"	Río Negro	"	)	)	,
(	268	,	(	"	San Juan de la Costa	"	)	)	,
(	269	,	(	"	San Pablo	"	)	)	,
(	270	,	(	"	Chaitén	"	)	)	,
(	271	,	(	"	Futaleufú	"	)	)	,
(	272	,	(	"	Hualaihué	"	)	)	,
(	273	,	(	"	Palena	"	)	)	,
(	274	,	(	"	Coihaique	"	)	)	,
(	275	,	(	"	Lago Verde	"	)	)	,
(	276	,	(	"	Aisén	"	)	)	,
(	277	,	(	"	Cisnes	"	)	)	,
(	278	,	(	"	Guaitecas	"	)	)	,
(	279	,	(	"	Cochrane	"	)	)	,
(	280	,	(	"	O'Higgins	"	)	)	,
(	281	,	(	"	Tortel	"	)	)	,
(	282	,	(	"	Chile Chico	"	)	)	,
(	283	,	(	"	Río Ibáñez	"	)	)	,
(	284	,	(	"	Punta Arenas	"	)	)	,
(	285	,	(	"	Laguna Blanca	"	)	)	,
(	286	,	(	"	Río Verde	"	)	)	,
(	287	,	(	"	San Gregorio	"	)	)	,
(	288	,	(	"	Cabo de Hornos	"	)	)	,
(	289	,	(	"	Antártica	"	)	)	,
(	290	,	(	"	Porvenir	"	)	)	,
(	291	,	(	"	Primavera	"	)	)	,
(	292	,	(	"	Timaukel	"	)	)	,
(	293	,	(	"	Natales	"	)	)	,
(	294	,	(	"	Torres del Paine	"	)	)	,
(	295	,	(	"	Santiago	"	)	)	,
(	296	,	(	"	Cerrillos	"	)	)	,
(	297	,	(	"	Cerro Navia	"	)	)	,
(	298	,	(	"	Conchalí	"	)	)	,
(	299	,	(	"	El Bosque	"	)	)	,
(	300	,	(	"	Estación Central	"	)	)	,
(	301	,	(	"	Huechuraba	"	)	)	,
(	302	,	(	"	Independencia	"	)	)	,
(	303	,	(	"	La Cisterna	"	)	)	,
(	304	,	(	"	La Florida	"	)	)	,
(	305	,	(	"	La Granja	"	)	)	,
(	306	,	(	"	La Pintana	"	)	)	,
(	307	,	(	"	La Reina	"	)	)	,
(	308	,	(	"	Las Condes	"	)	)	,
(	309	,	(	"	Lo Barnechea	"	)	)	,
(	310	,	(	"	Lo Espejo	"	)	)	,
(	311	,	(	"	Lo Prado	"	)	)	,
(	312	,	(	"	Macul	"	)	)	,
(	313	,	(	"	Maipú	"	)	)	,
(	314	,	(	"	Ñuñoa	"	)	)	,
(	315	,	(	"	Pedro Aguirre Cerda	"	)	)	,
(	316	,	(	"	Peñalolén	"	)	)	,
(	317	,	(	"	Providencia	"	)	)	,
(	318	,	(	"	Pudahuel	"	)	)	,
(	319	,	(	"	Quilicura	"	)	)	,
(	320	,	(	"	Quinta Normal	"	)	)	,
(	321	,	(	"	Recoleta	"	)	)	,
(	322	,	(	"	Renca	"	)	)	,
(	323	,	(	"	San Joaquín	"	)	)	,
(	324	,	(	"	San Miguel	"	)	)	,
(	325	,	(	"	San Ramón	"	)	)	,
(	326	,	(	"	Vitacura	"	)	)	,
(	327	,	(	"	Puente Alto	"	)	)	,
(	328	,	(	"	Pirque	"	)	)	,
(	329	,	(	"	San José de Maipo	"	)	)	,
(	330	,	(	"	Colina	"	)	)	,
(	331	,	(	"	Lampa	"	)	)	,
(	332	,	(	"	Tiltil	"	)	)	,
(	333	,	(	"	San Bernardo	"	)	)	,
(	334	,	(	"	Buin	"	)	)	,
(	335	,	(	"	Calera de Tango	"	)	)	,
(	336	,	(	"	Paine	"	)	)	,
(	337	,	(	"	Melipilla	"	)	)	,
(	338	,	(	"	Alhué	"	)	)	,
(	339	,	(	"	Curacaví	"	)	)	,
(	340	,	(	"	María Pinto	"	)	)	,
(	341	,	(	"	San Pedro	"	)	)	,
(	342	,	(	"	Talagante	"	)	)	,
(	343	,	(	"	El Monte	"	)	)	,
(	344	,	(	"	Isla de Maipo	"	)	)	,
(	345	,	(	"	Padre Hurtado	"	)	)	,
(	346	,	(	"	Peñaflor	"	)	)	,
(	347	,	(	"	Ignorada	"	)	)	

)
